//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class sysBpmsDepartmentMember
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public System.Guid ID { get; set; }
        [ForeignKey(nameof(Department))]
        public System.Guid DepartmentID { get; set; }
        public int RoleLU { get; set; }
        [ForeignKey(nameof(User))]
        public System.Guid UserID { get; set; }
    
        public virtual sysBpmsDepartment Department { get; set; }
        public virtual sysBpmsUser User { get; set; }
    }
}
