//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class sysBpmsLUTable
    {
        
        public sysBpmsLUTable()
        {
            this.LURows = new HashSet<sysBpmsLURow>();
        }
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public System.Guid ID { get; set; }
        public string NameOf { get; set; }
        public string Alias { get; set; }
        public bool IsSystemic { get; set; }
        public bool IsActive { get; set; }
    
        
        public virtual ICollection<sysBpmsLURow> LURows { get; set; }
    }
}
