//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class sysBpmsElement
    {
        
        public sysBpmsElement()
        {
            this.Events = new HashSet<sysBpmsEvent>();
            this.Gateways = new HashSet<sysBpmsGateway>();
            this.Lanes = new HashSet<sysBpmsLane>();
            this.SequenceFlows = new HashSet<sysBpmsSequenceFlow>();
            this.Tasks = new HashSet<sysBpmsTask>();
        }
        public string ID { get; set; }
        public string Name { get; set; }
        public int TypeLU { get; set; }
        [ForeignKey(nameof(Process))]
        public System.Guid ProcessID { get; set; }
    
        public virtual sysBpmsProcess Process { get; set; }
        
        public virtual ICollection<sysBpmsEvent> Events { get; set; }
        
        public virtual ICollection<sysBpmsGateway> Gateways { get; set; }
        
        public virtual ICollection<sysBpmsLane> Lanes { get; set; }
        
        public virtual ICollection<sysBpmsSequenceFlow> SequenceFlows { get; set; }
        
        public virtual ICollection<sysBpmsTask> Tasks { get; set; }
    }
}
