//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class sysBpmsEvent
    {
        
        public sysBpmsEvent()
        {
            this.ThreadEvents = new HashSet<sysBpmsThreadEvent>();
        }
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public System.Guid ID { get; set; }
        [ForeignKey(nameof(Element))]
        public string ElementID { get; set; }
        public int TypeLU { get; set; }
        public string ConfigurationXML { get; set; }
        public Nullable<int> SubType { get; set; }
        public string RefElementID { get; set; }
        public Nullable<bool> CancelActivity { get; set; }
        [ForeignKey(nameof(Process))]
        public System.Guid ProcessID { get; set; }
        [ForeignKey(nameof(MessageType))]
        public Nullable<System.Guid> MessageTypeID { get; set; }
    
        public virtual sysBpmsElement Element { get; set; }
        public virtual sysBpmsMessageType MessageType { get; set; }
        public virtual sysBpmsProcess Process { get; set; }
        
        public virtual ICollection<sysBpmsThreadEvent> ThreadEvents { get; set; }
    }
}
