//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class sysBpmsDocumentDef
    {
        
        public sysBpmsDocumentDef()
        {
            this.Documents = new HashSet<sysBpmsDocument>();
        }
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public System.Guid ID { get; set; }
        [ForeignKey(nameof(DocumentFolder))]
        public System.Guid DocumentFolderID { get; set; }
        public string NameOf { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> MaxSize { get; set; }
        public string ValidExtentions { get; set; }
        public bool IsMandatory { get; set; }
        public string Description { get; set; }
        public bool IsSystemic { get; set; }
        public bool IsActive { get; set; }
    
        
        public virtual ICollection<sysBpmsDocument> Documents { get; set; }
        public virtual sysBpmsDocumentFolder DocumentFolder { get; set; }
    }
}
