//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysBpmsAPIAccess
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string IPAddress { get; set; }
        public string AccessKey { get; set; }
        public bool IsActive { get; set; }
    }
}
