//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysBpmsEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sysBpmsEvent()
        {
            this.sysBpmsThreadEvents = new HashSet<sysBpmsThreadEvent>();
        }
    
        public System.Guid ID { get; set; }
        public string ElementID { get; set; }
        public int TypeLU { get; set; }
        public string ConfigurationXML { get; set; }
        public Nullable<int> SubType { get; set; }
        public string RefElementID { get; set; }
        public Nullable<bool> CancelActivity { get; set; }
        public System.Guid ProcessID { get; set; }
        public Nullable<System.Guid> MessageTypeID { get; set; }
    
        public virtual sysBpmsElement sysBpmsElement { get; set; }
        public virtual sysBpmsMessageType sysBpmsMessageType { get; set; }
        public virtual sysBpmsProcess sysBpmsProcess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsThreadEvent> sysBpmsThreadEvents { get; set; }
    }
}
