//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysBpmsLane
    {
        public System.Guid ID { get; set; }
        public string ElementID { get; set; }
        public System.Guid ProcessID { get; set; }
    
        public virtual sysBpmsElement sysBpmsElement { get; set; }
        public virtual sysBpmsProcess sysBpmsProcess { get; set; }
    }
}
