//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysBpmsApplicationPage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sysBpmsApplicationPage()
        {
            this.sysBpmsApplicationPageAccesses = new HashSet<sysBpmsApplicationPageAccess>();
            this.sysBpmsDynamicForms = new HashSet<sysBpmsDynamicForm>();
            this.sysBpmsVariables = new HashSet<sysBpmsVariable>();
        }
    
        public System.Guid ID { get; set; }
        public int GroupLU { get; set; }
        public string Description { get; set; }
        public bool ShowInMenu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsApplicationPageAccess> sysBpmsApplicationPageAccesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsDynamicForm> sysBpmsDynamicForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsVariable> sysBpmsVariables { get; set; }
    }
}
