//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysBpmsProcessGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sysBpmsProcessGroup()
        {
            this.sysBpmsProcesses = new HashSet<sysBpmsProcess>();
            this.sysBpmsProcessGroup1 = new HashSet<sysBpmsProcessGroup>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ProcessGroupID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsProcess> sysBpmsProcesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsProcessGroup> sysBpmsProcessGroup1 { get; set; }
        public virtual sysBpmsProcessGroup sysBpmsProcessGroup2 { get; set; }
    }
}
