//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysBpmsProcess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sysBpmsProcess()
        {
            this.sysBpmsDynamicForms = new HashSet<sysBpmsDynamicForm>();
            this.sysBpmsElements = new HashSet<sysBpmsElement>();
            this.sysBpmsEvents = new HashSet<sysBpmsEvent>();
            this.sysBpmsGateways = new HashSet<sysBpmsGateway>();
            this.sysBpmsLanes = new HashSet<sysBpmsLane>();
            this.sysBpmsProcess1 = new HashSet<sysBpmsProcess>();
            this.sysBpmsSequenceFlows = new HashSet<sysBpmsSequenceFlow>();
            this.sysBpmsTasks = new HashSet<sysBpmsTask>();
            this.sysBpmsThreads = new HashSet<sysBpmsThread>();
            this.sysBpmsVariables = new HashSet<sysBpmsVariable>();
        }
    
        public System.Guid ID { get; set; }
        public string FormattedNumber { get; set; }
        public Nullable<int> Number { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProcessVersion { get; set; }
        public Nullable<int> StatusLU { get; set; }
        public string CreatorUsername { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string DiagramXML { get; set; }
        public string WorkflowXML { get; set; }
        public string BeginTasks { get; set; }
        public Nullable<System.Guid> ParentProcessID { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<int> ParallelCountPerUser { get; set; }
        public string SourceCode { get; set; }
        public System.Guid ProcessGroupID { get; set; }
        public int TypeLU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsDynamicForm> sysBpmsDynamicForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsElement> sysBpmsElements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsEvent> sysBpmsEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsGateway> sysBpmsGateways { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsLane> sysBpmsLanes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsProcess> sysBpmsProcess1 { get; set; }
        public virtual sysBpmsProcess sysBpmsProcess2 { get; set; }
        public virtual sysBpmsProcessGroup sysBpmsProcessGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsSequenceFlow> sysBpmsSequenceFlows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsTask> sysBpmsTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsThread> sysBpmsThreads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsVariable> sysBpmsVariables { get; set; }
    }
}
