//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysBpmsDocument
    {
        public System.Guid GUID { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid DocumentDefID { get; set; }
        public Nullable<System.Guid> EntityDefID { get; set; }
        public Nullable<System.Guid> EntityID { get; set; }
        public Nullable<System.Guid> ThreadID { get; set; }
        public System.DateTime AtachDateOf { get; set; }
        public string FileExtention { get; set; }
        public string CaptionOf { get; set; }
    
        public virtual sysBpmsDocumentDef sysBpmsDocumentDef { get; set; }
        public virtual sysBpmsEntityDef sysBpmsEntityDef { get; set; }
        public virtual sysBpmsThread sysBpmsThread { get; set; }
    }
}
