//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysBpmsThreadVariable
    {
        public System.Guid ID { get; set; }
        public System.Guid ThreadID { get; set; }
        public System.Guid VariableID { get; set; }
        public string Value { get; set; }
    
        public virtual sysBpmsThread sysBpmsThread { get; set; }
        public virtual sysBpmsVariable sysBpmsVariable { get; set; }
    }
}
