//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysBpmsSettingValue
    {
        public System.Guid ID { get; set; }
        public System.Guid SettingDefID { get; set; }
        public System.DateTime SetDate { get; set; }
        public string UserName { get; set; }
        public string Value { get; set; }
    
        public virtual sysBpmsSettingDef sysBpmsSettingDef { get; set; }
    }
}
