//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysBpmsTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sysBpmsTask()
        {
            this.sysBpmsSteps = new HashSet<sysBpmsStep>();
            this.sysBpmsThreadTasks = new HashSet<sysBpmsThreadTask>();
        }
    
        public System.Guid ID { get; set; }
        public string ElementID { get; set; }
        public int TypeLU { get; set; }
        public string Code { get; set; }
        public Nullable<int> MarkerTypeLU { get; set; }
        public Nullable<int> OwnerTypeLU { get; set; }
        public string RoleName { get; set; }
        public string Rule { get; set; }
        public string UserID { get; set; }
        public System.Guid ProcessID { get; set; }
    
        public virtual sysBpmsElement sysBpmsElement { get; set; }
        public virtual sysBpmsProcess sysBpmsProcess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsStep> sysBpmsSteps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsThreadTask> sysBpmsThreadTasks { get; set; }
    }
}
