//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysBpmsThread
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sysBpmsThread()
        {
            this.sysBpmsDocuments = new HashSet<sysBpmsDocument>();
            this.sysBpmsThreadEvents = new HashSet<sysBpmsThreadEvent>();
            this.sysBpmsThreadTasks = new HashSet<sysBpmsThreadTask>();
            this.sysBpmsThreadVariables = new HashSet<sysBpmsThreadVariable>();
        }
    
        public System.Guid ID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int StatusLU { get; set; }
        public string GatewayStatusXml { get; set; }
        public System.Guid ProcessID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string FormattedNumber { get; set; }
        public Nullable<int> Number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsDocument> sysBpmsDocuments { get; set; }
        public virtual sysBpmsProcess sysBpmsProcess { get; set; }
        public virtual sysBpmsUser sysBpmsUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsThreadEvent> sysBpmsThreadEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsThreadTask> sysBpmsThreadTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsThreadVariable> sysBpmsThreadVariables { get; set; }
    }
}
