//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysBpmsGateway
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sysBpmsGateway()
        {
            this.sysBpmsConditions = new HashSet<sysBpmsCondition>();
        }
    
        public System.Guid ID { get; set; }
        public string ElementID { get; set; }
        public Nullable<System.Guid> DefaultSequenceFlowID { get; set; }
        public Nullable<int> TypeLU { get; set; }
        public string TraceToStart { get; set; }
        public System.Guid ProcessID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsCondition> sysBpmsConditions { get; set; }
        public virtual sysBpmsElement sysBpmsElement { get; set; }
        public virtual sysBpmsProcess sysBpmsProcess { get; set; }
        public virtual sysBpmsSequenceFlow sysBpmsSequenceFlow { get; set; }
    }
}
