//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysBpmsThreadTaskDelay
    {
        public System.Guid ID { get; set; }
        public System.Guid ThreadTaskID { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime UntillDate { get; set; }
        public string Description { get; set; }
    
        public virtual sysBpmsThreadTask sysBpmsThreadTask { get; set; }
    }
}
