//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysBpmsVariable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sysBpmsVariable()
        {
            this.sysBpmsThreadVariables = new HashSet<sysBpmsThreadVariable>();
            this.sysBpmsVariableDependencies = new HashSet<sysBpmsVariableDependency>();
            this.sysBpmsVariableDependencies1 = new HashSet<sysBpmsVariableDependency>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ProcessID { get; set; }
        public Nullable<System.Guid> ApplicationPageID { get; set; }
        public Nullable<System.Guid> EntityDefID { get; set; }
        public Nullable<System.Guid> DBConnectionID { get; set; }
        public string Name { get; set; }
        public int VarTypeLU { get; set; }
        public string FieldName { get; set; }
        public string Query { get; set; }
        public Nullable<int> FilterTypeLU { get; set; }
        public string Collection { get; set; }
        public string DefaultValue { get; set; }
        public string WhereClause { get; set; }
        public string OrderByClause { get; set; }
    
        public virtual sysBpmsApplicationPage sysBpmsApplicationPage { get; set; }
        public virtual sysBpmsDBConnection sysBpmsDBConnection { get; set; }
        public virtual sysBpmsEntityDef sysBpmsEntityDef { get; set; }
        public virtual sysBpmsProcess sysBpmsProcess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsThreadVariable> sysBpmsThreadVariables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsVariableDependency> sysBpmsVariableDependencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsVariableDependency> sysBpmsVariableDependencies1 { get; set; }
    }
}
