//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysBpmsApplicationPageAccess
    {
        public System.Guid ID { get; set; }
        public System.Guid ApplicationPageID { get; set; }
        public Nullable<System.Guid> DepartmentID { get; set; }
        public Nullable<int> RoleLU { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public bool AllowAdd { get; set; }
        public bool AllowEdit { get; set; }
        public bool AllowDelete { get; set; }
        public bool AllowView { get; set; }
    
        public virtual sysBpmsApplicationPage sysBpmsApplicationPage { get; set; }
        public virtual sysBpmsDepartment sysBpmsDepartment { get; set; }
        public virtual sysBpmsUser sysBpmsUser { get; set; }
    }
}
