//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysBpmsCondition
    {
        public System.Guid ID { get; set; }
        public System.Guid GatewayID { get; set; }
        public Nullable<System.Guid> SequenceFlowID { get; set; }
        public string Code { get; set; }
    
        public virtual sysBpmsGateway sysBpmsGateway { get; set; }
        public virtual sysBpmsSequenceFlow sysBpmsSequenceFlow { get; set; }
    }
}
