//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysBpmsVariableDependency
    {
        public System.Guid ID { get; set; }
        public System.Guid DependentVariableID { get; set; }
        public string DependentPropertyName { get; set; }
        public Nullable<System.Guid> ToVariableID { get; set; }
        public string ToPropertyName { get; set; }
        public string Description { get; set; }
    
        public virtual sysBpmsVariable sysBpmsVariable { get; set; }
        public virtual sysBpmsVariable sysBpmsVariable1 { get; set; }
    }
}
