//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysBpmsDepartmentMember
    {
        public System.Guid ID { get; set; }
        public System.Guid DepartmentID { get; set; }
        public int RoleLU { get; set; }
        public System.Guid UserID { get; set; }
    
        public virtual sysBpmsDepartment sysBpmsDepartment { get; set; }
        public virtual sysBpmsUser sysBpmsUser { get; set; }
    }
}
