//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysBpmsSequenceFlow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sysBpmsSequenceFlow()
        {
            this.sysBpmsConditions = new HashSet<sysBpmsCondition>();
            this.sysBpmsGateways = new HashSet<sysBpmsGateway>();
        }
    
        public System.Guid ID { get; set; }
        public string ElementID { get; set; }
        public System.Guid ProcessID { get; set; }
        public string Name { get; set; }
        public string SourceElementID { get; set; }
        public string TargetElementID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsCondition> sysBpmsConditions { get; set; }
        public virtual sysBpmsElement sysBpmsElement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsGateway> sysBpmsGateways { get; set; }
        public virtual sysBpmsProcess sysBpmsProcess { get; set; }
    }
}
