//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysBpmsDepartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sysBpmsDepartment()
        {
            this.sysBpmsApplicationPageAccesses = new HashSet<sysBpmsApplicationPageAccess>();
            this.sysBpmsDepartment1 = new HashSet<sysBpmsDepartment>();
            this.sysBpmsDepartmentMembers = new HashSet<sysBpmsDepartmentMember>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> DepartmentID { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsApplicationPageAccess> sysBpmsApplicationPageAccesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsDepartment> sysBpmsDepartment1 { get; set; }
        public virtual sysBpmsDepartment sysBpmsDepartment2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsDepartmentMember> sysBpmsDepartmentMembers { get; set; }
    }
}
