//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysBpmsDocumentDef
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sysBpmsDocumentDef()
        {
            this.sysBpmsDocuments = new HashSet<sysBpmsDocument>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid DocumentFolderID { get; set; }
        public string NameOf { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> MaxSize { get; set; }
        public string ValidExtentions { get; set; }
        public bool IsMandatory { get; set; }
        public string Description { get; set; }
        public bool IsSystemic { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsDocument> sysBpmsDocuments { get; set; }
        public virtual sysBpmsDocumentFolder sysBpmsDocumentFolder { get; set; }
    }
}
