//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysBpmsDynamicForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sysBpmsDynamicForm()
        {
            this.sysBpmsSteps = new HashSet<sysBpmsStep>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ProcessId { get; set; }
        public Nullable<System.Guid> ApplicationPageID { get; set; }
        public string Name { get; set; }
        public string DesignJson { get; set; }
        public string OnExitFormCode { get; set; }
        public string OnEntryFormCode { get; set; }
        public Nullable<int> Version { get; set; }
        public string ConfigXML { get; set; }
        public Nullable<bool> ShowInOverview { get; set; }
        public string SourceCode { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual sysBpmsApplicationPage sysBpmsApplicationPage { get; set; }
        public virtual sysBpmsProcess sysBpmsProcess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsStep> sysBpmsSteps { get; set; }
    }
}
