//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBusiness.BPMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysBpmsDocumentFolder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sysBpmsDocumentFolder()
        {
            this.sysBpmsDocumentDefs = new HashSet<sysBpmsDocumentDef>();
            this.sysBpmsDocumentFolder1 = new HashSet<sysBpmsDocumentFolder>();
        }
    
        public System.Guid ID { get; set; }
        public string NameOf { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.Guid> DocumentFolderID { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsDocumentDef> sysBpmsDocumentDefs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysBpmsDocumentFolder> sysBpmsDocumentFolder1 { get; set; }
        public virtual sysBpmsDocumentFolder sysBpmsDocumentFolder2 { get; set; }
    }
}
